version: '3'

services:
  webpage:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "80"
    volumes:
      - ./:/application:delegated
    restart: always
    stdin_open: true
    tty: true
